"""
HTML Report Generator — produces beautiful HTML report for sharing and archiving.

Generates a self-contained HTML file with:
- Executive summary with metrics
- Agent inventory table
- Policy violations with severity badges
- Framework detection results
- Scan metadata
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from agentgovern.policy.engine import PolicyCheckResult, PolicyViolation
    from agentgovern.scanner.codeprint import CodeprintScanResult

SEVERITY_COLORS = {
    "CRITICAL": "#dc2626",  # red-600
    "HIGH": "#ea580c",      # orange-600
    "MEDIUM": "#ca8a04",    # yellow-600
    "LOW": "#16a34a",       # green-600
}

RISK_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#ea580c",
    "MEDIUM": "#ca8a04",
    "LOW": "#16a34a",
}


def build_html_report(
    abom: dict[str, Any],
    policy_result: "PolicyCheckResult",
    codeprint_result: "CodeprintScanResult",
) -> str:
    """
    Build a self-contained HTML report from ABOM and scan results.

    Args:
        abom: Agent Bill of Materials dictionary
        policy_result: Policy check results
        codeprint_result: Code scanning results

    Returns:
        Complete HTML document as string
    """
    summary = abom.get("summary", {})
    agents = abom.get("agents", [])
    frameworks = abom.get("frameworks_detected", [])
    metadata = abom.get("metadata", {})

    # Build executive summary
    exec_summary = _build_executive_summary(summary)

    # Build agents table
    agents_table = _build_agents_table(agents)

    # Build violations section
    violations_section = _build_violations_section(policy_result)

    # Build frameworks section
    frameworks_section = _build_frameworks_section(frameworks)

    # Build secrets warning
    secrets_section = _build_secrets_section(codeprint_result)

    # Build metadata footer
    metadata_footer = _build_metadata_footer(metadata)

    # Assemble full HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="AgentGovern OS">
    <title>AgentGovern Scan Report — {metadata.get('project_name', 'Project')}</title>
    <style>
        {_get_css}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🛡️ AgentGovern OS</h1>
            <p class="subtitle">AI Agent Governance Scan Report</p>
        </header>

        {exec_summary}
        {agents_table}
        {violations_section}
        {secrets_section}
        {frameworks_section}
        {metadata_footer}

        <footer class="footer">
            <p>Generated by <a href="https://github.com/Ritinpaul/AgentGovern-OS" target="_blank">AgentGovern OS</a> — The open-source governance scanner for AI agents</p>
        </footer>
    </div>
</body>
</html>
"""
    return html


def _build_executive_summary(summary: dict[str, Any]) -> str:
    """Build the executive summary section."""
    passed = summary.get("overall_pass", False)
    status_class = "status-pass" if passed else "status-fail"
    status_text = "✓ PASSED" if passed else "✗ FAILED"

    critical = summary.get("critical", 0)
    high = summary.get("high", 0)
    medium = summary.get("medium", 0)
    low = summary.get("low", 0)
    secrets = summary.get("hardcoded_secrets", 0)
    total_agents = summary.get("total_agents", 0)

    return f"""
    <section class="executive-summary">
        <h2>Executive Summary</h2>
        <div class="status-badge {status_class}">{status_text}</div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-value">{total_agents}</div>
                <div class="metric-label">Total Agents</div>
            </div>
            <div class="metric-card severity-critical">
                <div class="metric-value">{critical}</div>
                <div class="metric-label">Critical</div>
            </div>
            <div class="metric-card severity-high">
                <div class="metric-value">{high}</div>
                <div class="metric-label">High</div>
            </div>
            <div class="metric-card severity-medium">
                <div class="metric-value">{medium}</div>
                <div class="metric-label">Medium</div>
            </div>
            <div class="metric-card severity-low">
                <div class="metric-value">{low}</div>
                <div class="metric-label">Low</div>
            </div>
            <div class="metric-card severity-critical">
                <div class="metric-value">{secrets}</div>
                <div class="metric-label">Hardcoded Secrets</div>
            </div>
        </div>
    </section>
    """


def _build_agents_table(agents: list[dict[str, Any]]) -> str:
    """Build the agents inventory table."""
    if not agents:
        return '<section><h2>🤖 Detected Agents</h2><p class="warning">No agents found in manifest.</p></section>'

    rows = []
    for agent in agents:
        code = agent.get("code", "")
        name = agent.get("name", "")
        framework = agent.get("framework", "—")
        tier = agent.get("tier") or "unset"
        authority = agent.get("authority_limit")
        currency = agent.get("currency", "USD")
        risk = agent.get("risk_level", "LOW")

        authority_str = f"{authority:,.2f} {currency}" if authority is not None else "unset"
        risk_color = RISK_COLORS.get(risk, "#6b7280")

        rows.append(f"""
        <tr>
            <td class="code-cell">{code}</td>
            <td>{name}</td>
            <td class="framework-cell">{framework}</td>
            <td class="tier-cell">{tier}</td>
            <td class="authority-cell">{authority_str}</td>
            <td><span class="risk-badge" style="background-color: {risk_color};">{risk}</span></td>
        </tr>
        """)

    return f"""
    <section>
        <h2>🤖 Detected Agents</h2>
        <table class="agents-table">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Framework</th>
                    <th>Tier</th>
                    <th>Authority Limit</th>
                    <th>Risk</th>
                </tr>
            </thead>
            <tbody>
                {"".join(rows)}
            </tbody>
        </table>
    </section>
    """


def _build_violations_section(policy_result: "PolicyCheckResult") -> str:
    """Build the policy violations section."""
    if not policy_result.violations:
        return '<section><h2>⚠️ Policy Violations</h2><p class="success">✅ No policy violations found!</p></section>'

    rows = []
    for v in policy_result.violations:
        sev_color = SEVERITY_COLORS.get(v.severity, "#6b7280")
        rows.append(f"""
        <tr>
            <td class="rule-id-cell">{v.rule_id}</td>
            <td><span class="severity-badge" style="background-color: {sev_color};">{v.severity}</span></td>
            <td class="agent-cell">{v.agent_code or "project"}</td>
            <td>{v.message}</td>
            <td class="suggestion-cell">{v.suggestion}</td>
        </tr>
        """)

    return f"""
    <section>
        <h2>⚠️ Policy Violations</h2>
        <table class="violations-table">
            <thead>
                <tr>
                    <th>Rule ID</th>
                    <th>Severity</th>
                    <th>Agent</th>
                    <th>Message</th>
                    <th>Suggestion</th>
                </tr>
            </thead>
            <tbody>
                {"".join(rows)}
            </tbody>
        </table>
    </section>
    """


def _build_secrets_section(codeprint_result: "CodeprintScanResult") -> str:
    """Build the hardcoded secrets warning section."""
    if not codeprint_result.secret_detections:
        return ""

    items = []
    for s in codeprint_result.secret_detections:
        items.append(f"""
        <div class="secret-item">
            <div class="secret-type">{s.secret_type}</div>
            <div class="secret-location">{s.file}:{s.line}</div>
            <code class="secret-snippet">{s.snippet}</code>
        </div>
        """)

    return f"""
    <section class="secrets-section">
        <h2>🔑 Hardcoded Secrets Detected</h2>
        <div class="secrets-list">
            {"".join(items)}
        </div>
    </section>
    """


def _build_frameworks_section(frameworks: list[dict[str, Any]]) -> str:
    """Build the detected frameworks section."""
    if not frameworks:
        return ""

    items = []
    for fw in frameworks:
        confidence = "HIGH CONFIDENCE" if fw.get("high_confidence") else "detected"
        conf_class = "conf-high" if fw.get("high_confidence") else "conf-medium"
        items.append(f"""
        <div class="framework-item">
            <span class="framework-name">{fw.get('framework', '')}</span>
            <span class="framework-package">({fw.get('package', '')})</span>
            <span class="framework-source">via {fw.get('source_file', '')}</span>
            <span class="confidence-badge {conf_class}">{confidence}</span>
        </div>
        """)

    return f"""
    <section>
        <h2>📦 AI Frameworks Detected</h2>
        <div class="frameworks-list">
            {"".join(items)}
        </div>
    </section>
    """


def _build_metadata_footer(metadata: dict[str, Any]) -> str:
    """Build the scan metadata footer."""
    project = metadata.get("project_name", "Unknown")
    timestamp = metadata.get("scan_timestamp", datetime.now.isoformat)
    duration = metadata.get("scan_duration_s", 0)

    return f"""
    <section class="metadata">
        <h3>Scan Metadata</h3>
        <dl>
            <dt>Project:</dt><dd>{project}</dd>
            <dt>Scan Time:</dt><dd>{timestamp}</dd>
            <dt>Duration:</dt><dd>{duration:.2f}s</dd>
            <dt>Scanner Version:</dt><dd>{metadata.get('scanner_version', 'unknown')}</dd>
        </dl>
    </section>
    """


def _get_css -> str:
    """Return the embedded CSS stylesheet."""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #1f2937;
            background: #f9fafb;
            padding: 2rem 1rem;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
            color: white;
            padding: 3rem 2rem;
            text-align: center;
        }

        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .subtitle {
            font-size: 1.1rem;
            opacity: 0.9;
        }

        section {
            padding: 2rem;
            border-bottom: 1px solid #e5e7eb;
        }

        section:last-of-type {
            border-bottom: none;
        }

        h2 {
            font-size: 1.75rem;
            margin-bottom: 1.5rem;
            color: #111827;
        }

        h3 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            color: #374151;
        }

        .executive-summary {
            background: #f9fafb;
        }

        .status-badge {
            display: inline-block;
            padding: 0.75rem 1.5rem;
            border-radius: 8px;
            font-size: 1.25rem;
            font-weight: 700;
            margin-bottom: 2rem;
        }

        .status-pass {
            background: #10b981;
            color: white;
        }

        .status-fail {
            background: #dc2626;
            color: white;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 1rem;
        }

        .metric-card {
            background: white;
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            padding: 1.5rem;
            text-align: center;
        }

        .metric-value {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }

        .metric-label {
            font-size: 0.875rem;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .severity-critical {
            border-color: #dc2626;
        }

        .severity-critical .metric-value {
            color: #dc2626;
        }

        .severity-high {
            border-color: #ea580c;
        }

        .severity-high .metric-value {
            color: #ea580c;
        }

        .severity-medium {
            border-color: #ca8a04;
        }

        .severity-medium .metric-value {
            color: #ca8a04;
        }

        .severity-low {
            border-color: #16a34a;
        }

        .severity-low .metric-value {
            color: #16a34a;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
        }

        thead {
            background: #f3f4f6;
        }

        th {
            padding: 1rem;
            text-align: left;
            font-weight: 600;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }

        td {
            padding: 1rem;
            border-bottom: 1px solid #f3f4f6;
        }

        tr:hover {
            background: #fafafa;
        }

        .code-cell {
            font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
            font-weight: 600;
            color: #10b981;
        }

        .framework-cell {
            color: #06b6d4;
        }

        .tier-cell {
            text-align: center;
        }

        .authority-cell {
            text-align: right;
            font-weight: 500;
        }

        .risk-badge, .severity-badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 700;
            color: white;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .rule-id-cell {
            font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
            font-size: 0.875rem;
            color: #6b7280;
        }

        .agent-cell {
            font-weight: 500;
        }

        .suggestion-cell {
            color: #6b7280;
            font-size: 0.875rem;
        }

        .success {
            color: #10b981;
            font-weight: 600;
            font-size: 1.1rem;
        }

        .warning {
            color: #ca8a04;
            font-weight: 600;
        }

        .secrets-section {
            background: #fef2f2;
            border-left: 4px solid #dc2626;
        }

        .secrets-list {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }

        .secret-item {
            background: white;
            padding: 1rem;
            border-radius: 6px;
            border: 1px solid #fecaca;
        }

        .secret-type {
            font-weight: 700;
            color: #dc2626;
            margin-bottom: 0.5rem;
        }

        .secret-location {
            font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
            font-size: 0.875rem;
            color: #6b7280;
            margin-bottom: 0.5rem;
        }

        .secret-snippet {
            display: block;
            background: #fef2f2;
            padding: 0.5rem;
            border-radius: 4px;
            font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
            font-size: 0.875rem;
            color: #991b1b;
        }

        .frameworks-list {
            display: flex;
            flex-direction: column;
            gap: 0.75rem;
        }

        .framework-item {
            background: #f0f9ff;
            border: 1px solid #bfdbfe;
            padding: 1rem;
            border-radius: 6px;
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }

        .framework-name {
            font-weight: 700;
            color: #0369a1;
        }

        .framework-package {
            color: #6b7280;
            font-size: 0.875rem;
        }

        .framework-source {
            color: #9ca3af;
            font-size: 0.875rem;
            flex: 1;
        }

        .confidence-badge {
            padding: 0.25rem 0.75rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 700;
            text-transform: uppercase;
        }

        .conf-high {
            background: #10b981;
            color: white;
        }

        .conf-medium {
            background: #06b6d4;
            color: white;
        }

        .metadata {
            background: #f9fafb;
        }

        dl {
            display: grid;
            grid-template-columns: auto 1fr;
            gap: 0.5rem 1rem;
        }

        dt {
            font-weight: 600;
            color: #374151;
        }

        dd {
            color: #6b7280;
        }

        .footer {
            text-align: center;
            padding: 2rem;
            background: #f9fafb;
            color: #6b7280;
            font-size: 0.875rem;
        }

        .footer a {
            color: #10b981;
            text-decoration: none;
            font-weight: 600;
        }

        .footer a:hover {
            text-decoration: underline;
        }
    """


def save_html_report(html: str, output_path: Path) -> None:
    """Save the HTML report to a file."""
    output_path.write_text(html, encoding="utf-8")
